<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Workshop: Quantitative analysis of ChiP-seq, ATAC-seq, and related DNA enrichment assays • QuantitativeChIPseqWorkshop</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/flatly/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Workshop: Quantitative analysis of ChiP-seq, ATAC-seq, and related DNA enrichment assays">
<meta property="og:description" content="QuantitativeChIPseqWorkshop">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-93043521-1"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-93043521-1');
</script>
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">QuantitativeChIPseqWorkshop</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.6</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Quantitative-ChIPseq-Workshop.html">Workshop: Quantitative analysis of ChiP-seq, ATAC-seq, and related DNA enrichment assays</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/bioinformatics-core-shared-training/Quantitative-ChIPseq-Workshop">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="Quantitative-ChIPseq-Workshop_files/accessible-code-block-0.0.1/empty-anchor.js"></script><link href="Quantitative-ChIPseq-Workshop_files/anchor-sections-1.0/anchor-sections.css" rel="stylesheet">
<script src="Quantitative-ChIPseq-Workshop_files/anchor-sections-1.0/anchor-sections.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Workshop: Quantitative analysis of ChiP-seq, ATAC-seq, and related DNA enrichment assays</h1>
                        <h4 class="author">Rory Stark</h4>
            <address class="author_afil">
      Cancer Research UK Cambridge Institute, University of Cambridge, Cambridge, UK<br><h4 class="date">December 07, 2020</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/bioinformatics-core-shared-training/Quantitative-ChIPseq-Workshop/blob/master/vignettes/Quantitative-ChIPseq-Workshop.Rmd"><code>vignettes/Quantitative-ChIPseq-Workshop.Rmd</code></a></small>
      <div class="hidden name"><code>Quantitative-ChIPseq-Workshop.Rmd</code></div>

    </address>
</div>

    
    
<style type="text/css">
.infobox {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  border: 2px solid #008000;
  border-radius: 10px;
  background: #DCDCDC 5px center/3em no-repeat;
  color: #8B0000;
}
.center {
  text-align: center;
}
</style>
<div id="quantitative-analysis-of-chip-seq-atac-seq-and-related-dna-enrichment-assays" class="section level1">
<h1 class="hasAnchor">
<a href="#quantitative-analysis-of-chip-seq-atac-seq-and-related-dna-enrichment-assays" class="anchor"></a>Quantitative analysis of ChiP-seq, ATAC-seq, and related DNA enrichment assays</h1>
<div id="workshop-participation" class="section level2">
<h2 class="hasAnchor">
<a href="#workshop-participation" class="anchor"></a>Workshop participation</h2>
<p>Docker users can run this workshop locally via:</p>
<pre><code>docker run -e PASSWORD=DiffBind -p 8787:8787 crukcibioinformatics/quantitative_chip_workshop:latest</code></pre>
<p>Then open a browser and go to the URL <strong>localhost:8787</strong>. Log into RStudio with <strong>username:rstudio</strong> and <strong>password:DiffBind</strong>.</p>
</div>
<div id="requirements-rbioconductor-packages" class="section level2">
<h2 class="hasAnchor">
<a href="#requirements-rbioconductor-packages" class="anchor"></a>Requirements: R/Bioconductor packages</h2>
<p>The workshop uses a Docker container with Bioconductor Release version <code>3.12</code>. If you would like to install Bioconductor on your computer <strong>at a later date</strong>, see the <a href="https://www.bioconductor.org/install">Bioconductor installation</a> instructions.</p>
<p>Here is a list of packages that we will be using:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.cruk.cam.ac.uk/core-facilities/bioinformatics-core/software/diffbind">DiffBind</a></span><span class="op">)</span></code></pre></div>
<pre><code>## Loading required package: GenomicRanges</code></pre>
<pre><code>## Loading required package: stats4</code></pre>
<pre><code>## Loading required package: BiocGenerics</code></pre>
<pre><code>## Loading required package: parallel</code></pre>
<pre><code>## 
## Attaching package: 'BiocGenerics'</code></pre>
<pre><code>## The following objects are masked from 'package:parallel':
## 
##     clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
##     clusterExport, clusterMap, parApply, parCapply, parLapply,
##     parLapplyLB, parRapply, parSapply, parSapplyLB</code></pre>
<pre><code>## The following objects are masked from 'package:stats':
## 
##     IQR, mad, sd, var, xtabs</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     anyDuplicated, append, as.data.frame, basename, cbind, colnames,
##     dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
##     grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
##     order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
##     rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
##     union, unique, unsplit, which.max, which.min</code></pre>
<pre><code>## Loading required package: S4Vectors</code></pre>
<pre><code>## 
## Attaching package: 'S4Vectors'</code></pre>
<pre><code>## The following object is masked from 'package:base':
## 
##     expand.grid</code></pre>
<pre><code>## Loading required package: IRanges</code></pre>
<pre><code>## Loading required package: GenomeInfoDb</code></pre>
<pre><code>## Loading required package: SummarizedExperiment</code></pre>
<pre><code>## Loading required package: MatrixGenerics</code></pre>
<pre><code>## Loading required package: matrixStats</code></pre>
<pre><code>## 
## Attaching package: 'MatrixGenerics'</code></pre>
<pre><code>## The following objects are masked from 'package:matrixStats':
## 
##     colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
##     colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
##     colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
##     colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
##     colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
##     colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
##     colWeightedMeans, colWeightedMedians, colWeightedSds,
##     colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
##     rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
##     rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
##     rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
##     rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
##     rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
##     rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
##     rowWeightedSds, rowWeightedVars</code></pre>
<pre><code>## Loading required package: Biobase</code></pre>
<pre><code>## Welcome to Bioconductor
## 
##     Vignettes contain introductory material; view with
##     'browseVignettes()'. To cite Bioconductor, see
##     'citation("Biobase")', and for packages 'citation("pkgname")'.</code></pre>
<pre><code>## 
## Attaching package: 'Biobase'</code></pre>
<pre><code>## The following object is masked from 'package:MatrixGenerics':
## 
##     rowMedians</code></pre>
<pre><code>## The following objects are masked from 'package:matrixStats':
## 
##     anyMissing, rowMedians</code></pre>
<pre><code>## </code></pre>
<pre><code>##  &gt;&gt;&gt; DiffBind 3.0 includes substantial updates. See ?DiffBind3 for details on what has changed.</code></pre>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">GreyListChIP</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">csaw</span><span class="op">)</span></code></pre></div>
</div>
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<div id="set-directory-to-where-the-data-are" class="section level3">
<h3 class="hasAnchor">
<a href="#set-directory-to-where-the-data-are" class="anchor"></a>Set directory to where the data are</h3>
<p>First make sure your current working directory is correct:</p>
<pre><code>## [1] "/__w/Quantitative-ChIPseq-Workshop/Quantitative-ChIPseq-Workshop/inst/extdata"</code></pre>
<p>The directory should be <code>"/home/rstudio/inst/extdata"</code>. If it is not, change the working directory:</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/getwd.html">setwd</a></span><span class="op">(</span><span class="st">"inst/extdata"</span><span class="op">)</span></code></pre></div>
</div>
</div>
<div id="loading-an-experiment-into-diffbind" class="section level2">
<h2 class="hasAnchor">
<a href="#loading-an-experiment-into-diffbind" class="anchor"></a>Loading an experiment into <code>DiffBind</code>
</h2>
<div id="what-do-you-need-to-do-a-quantitiative-analysis-of-an-experiment" class="section level3">
<h3 class="hasAnchor">
<a href="#what-do-you-need-to-do-a-quantitiative-analysis-of-an-experiment" class="anchor"></a>What do you need to do a quantitiative analysis of an experiment?</h3>
<p>In order to run an quantitative analysis, all the experimental data must be ready. This includes three types of data:</p>
<div id="sample-metadata" class="section level4">
<h4 class="hasAnchor">
<a href="#sample-metadata" class="anchor"></a>Sample metadata</h4>
<p>An experiment is based on a number of <strong>samples</strong>. Each sample needs a unique <strong>SampleID</strong>. A comparative analysis requires that the samples are associated with at least two classes that can be compared. The classes the samples belong to are indicated by associated samples <em>metadata</em>, which can include:</p>
<ul>
<li>
<strong>Factor</strong> - for ChIPs, this is usually what protein the antibody was targeting, such as a transcription factor or a histone mark.</li>
<li>
<strong>Tissue</strong> - a designation for the cell type, tissue type, or some other indication of the biological source of the material.</li>
<li>
<strong>Condition</strong> - an experimental condition, such as WT or Mutant.</li>
<li>
<strong>Treatment</strong> - an indication of how the cells were treated.</li>
</ul>
<p>Note that not all of these are required, but there should be at least one metadata factor to divide the samples into classes.</p>
<p>Finally it is imperative that the experimental classes be represented by <strong>Replicate</strong> samples. <em>It is not possible to perform a meaningful quantitative analysis without replicated data to capture variance.</em> Generally a minimum of three replicates are required to obtain meaningful results.</p>
</div>
<div id="aligned-sequencing-read-data" class="section level4">
<h4 class="hasAnchor">
<a href="#aligned-sequencing-read-data" class="anchor"></a>Aligned sequencing read data</h4>
<p>The second type of data needed for an analysis are aligned sequencing reads, generally in the form of ‘.bam’ files. Each sample needs an aligned sequencing library, but may include the following:</p>
<ul>
<li>
<strong>bamReads</strong> - the primary aligned reads for the ChIP, ATAC, or other assay.</li>
<li>
<strong>bamControl</strong> - an optional set of control reads associated with the sample or sample class. For ChIP experiments, this is most often an Input control (ChIP run without an antibody), or a ChIP run with a non-specific antibody. ATAC experiment usually do not have a control.</li>
<li>
<strong>SpikeIn</strong> - an option set of spike-in reads for normalization.</li>
</ul>
</div>
<div id="called-peaks" class="section level4">
<h4 class="hasAnchor">
<a href="#called-peaks" class="anchor"></a>Called peaks</h4>
<p>The type of analysis we are discussing today requires that a peak caller (such as <strong>MACS</strong>) has been used on the aligned reads to call peaks. While having called peaks for the sample is useful in a variety of ways, it is possible to perform a quantitative analysis without using called peaks. For example, in some cases, the regions of interest may be known in advance (such as a list known gene promoters). An alternative is to perform a quantitative analysis using windows that cover the entire genome. The <code>csaw</code> package <span class="citation">(Lun and Smyth 2016)</span> provides a tool to perform such an analysis.</p>
</div>
</div>
<div id="making-a-samplesheet" class="section level3">
<h3 class="hasAnchor">
<a href="#making-a-samplesheet" class="anchor"></a>Making a samplesheet</h3>
<p>The easiest way to set up an experiment for analysis in <code>DiffBind</code>is to use a <em>sample sheet</em>. This can take the form of a <code>.csv</code> file, or a <code>dataframe</code>.</p>
<p>We can read in the sample sheet provided for the example data set:</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">samples</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"tamoxifen.csv"</span><span class="op">)</span>
<span class="va">samples</span></code></pre></div>
<pre><code>##    SampleID Tissue Factor  Condition  Treatment Replicate
## 1    BT4741  BT474     ER  Resistant Full-Media         1
## 2    BT4742  BT474     ER  Resistant Full-Media         2
## 3     MCF71   MCF7     ER Responsive Full-Media         1
## 4     MCF72   MCF7     ER Responsive Full-Media         2
## 5     MCF73   MCF7     ER Responsive Full-Media         3
## 6     T47D1   T47D     ER Responsive Full-Media         1
## 7     T47D2   T47D     ER Responsive Full-Media         2
## 8    MCF7r1   MCF7     ER  Resistant Full-Media         1
## 9    MCF7r2   MCF7     ER  Resistant Full-Media         2
## 10    ZR751   ZR75     ER Responsive Full-Media         1
## 11    ZR752   ZR75     ER Responsive Full-Media         2
##                      bamReads ControlID                  bamControl
## 1  reads/Chr18_BT474_ER_1.bam    BT474c reads/Chr18_BT474_input.bam
## 2  reads/Chr18_BT474_ER_2.bam    BT474c reads/Chr18_BT474_input.bam
## 3   reads/Chr18_MCF7_ER_1.bam     MCF7c  reads/Chr18_MCF7_input.bam
## 4   reads/Chr18_MCF7_ER_2.bam     MCF7c  reads/Chr18_MCF7_input.bam
## 5   reads/Chr18_MCF7_ER_3.bam     MCF7c  reads/Chr18_MCF7_input.bam
## 6   reads/Chr18_T47D_ER_1.bam     T47Dc  reads/Chr18_T47D_input.bam
## 7   reads/Chr18_T47D_ER_2.bam     T47Dc  reads/Chr18_T47D_input.bam
## 8   reads/Chr18_TAMR_ER_1.bam     TAMRc  reads/Chr18_TAMR_input.bam
## 9   reads/Chr18_TAMR_ER_2.bam     TAMRc  reads/Chr18_TAMR_input.bam
## 10  reads/Chr18_ZR75_ER_1.bam     ZR75c  reads/Chr18_ZR75_input.bam
## 11  reads/Chr18_ZR75_ER_2.bam     ZR75c  reads/Chr18_ZR75_input.bam
##                      Peaks PeakCaller
## 1  peaks/BT474_ER_1.bed.gz        bed
## 2  peaks/BT474_ER_2.bed.gz        bed
## 3   peaks/MCF7_ER_1.bed.gz        bed
## 4   peaks/MCF7_ER_2.bed.gz        bed
## 5   peaks/MCF7_ER_3.bed.gz        bed
## 6   peaks/T47D_ER_1.bed.gz        bed
## 7   peaks/T47D_ER_2.bed.gz        bed
## 8   peaks/TAMR_ER_1.bed.gz        bed
## 9   peaks/TAMR_ER_2.bed.gz        bed
## 10  peaks/ZR75_ER_1.bed.gz        bed
## 11  peaks/ZR75_ER_2.bed.gz        bed</code></pre>
<p>Here we see the example ChIP-seq data set used for this tutorial. It consists of 11 samples, all ChIPed for the same factor (ER, the estrogen receptor). There are four breast-cancer cell lines involved, representing two experimental conditions: cells that either <code>Responsive</code> to the drug tamoxifen, or those that are <code>Resistant</code> to tamoxifen. Note that one cell line (MCF7) is marked as being both <code>Resposnsive</code>and <code>Resistant</code>; these cells are naturally <code>Responsive</code>, but a <code>Resistant</code> version has been derived by treating with tamoxifen until only resistant cells remain. The goal of the experiment is to examine changes in ER binding patterns between the two conditions.</p>
<p>There are seven replicates of <code>Responsive</code> samples, encompassing three different cell lines, with two or three replicates for each <code>Responsive</code>cell line. There are four replicates of <code>Resistant</code> samples in two cell lines, each with two replicates. For each sample we have a set of aligned reads (note that only reads aligned to chromosome 18 are included to speed up the example analysis), and an Input control is available for each cell line/condition combination.</p>
<p>Peaks are included in <code>.bed</code> format (they were originally called using <code>MACS</code> <span class="citation">(Zhang et al. 2008)</span>.)</p>
</div>
<div id="loading-the-experiment-into-diffbind" class="section level3">
<h3 class="hasAnchor">
<a href="#loading-the-experiment-into-diffbind" class="anchor"></a>Loading the experiment into <code>DiffBind</code>
</h3>
<p>At this point a complete default end-to-end analysis could be run using a single command: <code>result &lt;- dba(samples)</code>. Instead, we are going to walk through each of the steps of the analysis one at a time.</p>
<p>First load the experiment into <code>DiffBind</code> either by supplying the original <code>.csv</code> file or using the loaded <code>samples</code> dataframe:</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.peaks</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.html">dba</a></span><span class="op">(</span>sampleSheet<span class="op">=</span><span class="st">"tamoxifen.csv"</span><span class="op">)</span></code></pre></div>
<pre><code>## BT4741 BT474 ER Resistant Full-Media 1 bed</code></pre>
<pre><code>## BT4742 BT474 ER Resistant Full-Media 2 bed</code></pre>
<pre><code>## MCF71 MCF7 ER Responsive Full-Media 1 bed</code></pre>
<pre><code>## MCF72 MCF7 ER Responsive Full-Media 2 bed</code></pre>
<pre><code>## MCF73 MCF7 ER Responsive Full-Media 3 bed</code></pre>
<pre><code>## T47D1 T47D ER Responsive Full-Media 1 bed</code></pre>
<pre><code>## T47D2 T47D ER Responsive Full-Media 2 bed</code></pre>
<pre><code>## MCF7r1 MCF7 ER Resistant Full-Media 1 bed</code></pre>
<pre><code>## MCF7r2 MCF7 ER Resistant Full-Media 2 bed</code></pre>
<pre><code>## ZR751 ZR75 ER Responsive Full-Media 1 bed</code></pre>
<pre><code>## ZR752 ZR75 ER Responsive Full-Media 2 bed</code></pre>
<p>This creates a <code>DBA</code> object we’ve called <code>tam.peaks</code>, which can be examined:</p>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.peaks</span></code></pre></div>
<pre><code>## 11 Samples, 2845 sites in matrix (3795 total):
##        ID Tissue Factor  Condition  Treatment Replicate Intervals
## 1  BT4741  BT474     ER  Resistant Full-Media         1      1080
## 2  BT4742  BT474     ER  Resistant Full-Media         2      1122
## 3   MCF71   MCF7     ER Responsive Full-Media         1      1556
## 4   MCF72   MCF7     ER Responsive Full-Media         2      1046
## 5   MCF73   MCF7     ER Responsive Full-Media         3      1339
## 6   T47D1   T47D     ER Responsive Full-Media         1       527
## 7   T47D2   T47D     ER Responsive Full-Media         2       373
## 8  MCF7r1   MCF7     ER  Resistant Full-Media         1      1438
## 9  MCF7r2   MCF7     ER  Resistant Full-Media         2       930
## 10  ZR751   ZR75     ER Responsive Full-Media         1      2346
## 11  ZR752   ZR75     ER Responsive Full-Media         2      2345</code></pre>
<p>This shows the metadata for the 11 samples, along with how many called peaks were included for each. After loading, overlapping peaks are merged; there are a total of 3,795 unique regions specified, with 2,845 of them overlapping peaks called in at least two samples.</p>
</div>
</div>
<div id="blacklists-and-greylists" class="section level2">
<h2 class="hasAnchor">
<a href="#blacklists-and-greylists" class="anchor"></a>Blacklists and greylists</h2>
<p>Now that the peaks are loaded, it is good practice to filter out peaks called in problematic regions. This is accomplished using a standard, published <code>Blacklist</code> of areas in in reference genome known to be problematic. The best known lists have been identified as part of the ENCODE project <span class="citation">(Amemiya, Kundaje, and Boyle 2019)</span> and are available for a variety of reference genomes and genome versions. The current ENCODE blacklists are available through the <code><a href="https://rdrr.io/pkg/DiffBind/man/dba.blacklist.html">dba.blacklist()</a></code> function.</p>
<p>In addition, if control alignments are available for an experiment, experiment-specific exclusion lists can be generated reflecting the tissue and experimental conditions used. We call these <code>Greylists</code> and are generated using the <code>GreyListChIP</code>package <span class="citation">(Brown 2015)</span>. The idea is to analyze libraries that are not meant to show systematic enrichment (such as Inputs, in which no anti-body is introduced), and identify anomalous regions where a disproportionate degree of signal is present.</p>
<div id="applying-a-blacklist" class="section level3">
<h3 class="hasAnchor">
<a href="#applying-a-blacklist" class="anchor"></a>Applying a blacklist</h3>
<p>If an ENCODE blacklists exists for the reference genome used to align the experimental data, it can be applied automatically using the <code><a href="https://rdrr.io/pkg/DiffBind/man/dba.blacklist.html">dba.blacklist()</a></code> function. The reference genome is automatically detected from the supplied <code>.bam</code> files.</p>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.blacklist.html">dba.blacklist</a></span><span class="op">(</span><span class="va">tam.peaks</span>, blacklist<span class="op">=</span><span class="cn">TRUE</span>, greylist<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<pre><code>## Genome detected: Hsapiens.UCSC.hg19</code></pre>
<pre><code>## Applying blacklist...</code></pre>
<pre><code>## Removed: 3 of 14102 intervals.</code></pre>
<pre><code>## Removed: 1 merged (of 3795) and 1 (of 2845) consensus.</code></pre>
<pre><code>## 11 Samples, 2844 sites in matrix (3794 total):
##        ID Tissue Factor  Condition  Treatment Replicate Intervals
## 1  BT4741  BT474     ER  Resistant Full-Media         1      1080
## 2  BT4742  BT474     ER  Resistant Full-Media         2      1122
## 3   MCF71   MCF7     ER Responsive Full-Media         1      1555
## 4   MCF72   MCF7     ER Responsive Full-Media         2      1045
## 5   MCF73   MCF7     ER Responsive Full-Media         3      1338
## 6   T47D1   T47D     ER Responsive Full-Media         1       527
## 7   T47D2   T47D     ER Responsive Full-Media         2       373
## 8  MCF7r1   MCF7     ER  Resistant Full-Media         1      1438
## 9  MCF7r2   MCF7     ER  Resistant Full-Media         2       930
## 10  ZR751   ZR75     ER Responsive Full-Media         1      2346
## 11  ZR752   ZR75     ER Responsive Full-Media         2      2345</code></pre>
<p>This shows that the blacklist filtered out one merged peak that had been called in three of the samples.</p>
</div>
<div id="generating-and-applying-a-greylist" class="section level3">
<h3 class="hasAnchor">
<a href="#generating-and-applying-a-greylist" class="anchor"></a>Generating and applying a greylist</h3>
<p>Greylists can be automatically generated from the controls as <code>DiffBind</code> provides an interface to the <code>GreyListChIP</code> package. This can be a time-consuming operation, as each of the controls is analyzed for anomalous regions.</p>
<p>The blacklist can be applied, and the greylists generated and applied, in a single step:</p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.peaks</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.blacklist.html">dba.blacklist</a></span><span class="op">(</span><span class="va">tam.peaks</span><span class="op">)</span></code></pre></div>
<p>To save time, greylists for the example data set are included, and we can apply them directly:</p>
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">tamoxifen_greylist</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">tamoxifen.greylist</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "master"   "controls"</code></pre>
<p>In this object, there is a “master” greylist formed from the individual greylist (computed one per control):</p>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tamoxifen.greylist</span><span class="op">$</span><span class="va">master</span></code></pre></div>
<pre><code>## GRanges object with 72 ranges and 0 metadata columns:
##        seqnames            ranges strand
##           &lt;Rle&gt;         &lt;IRanges&gt;  &lt;Rle&gt;
##    [1]    chr18        9217-11264      *
##    [2]    chr18     105473-112128      *
##    [3]    chr18     267265-268800      *
##    [4]    chr18     402433-403456      *
##    [5]    chr18     504832-505855      *
##    ...      ...               ...    ...
##   [68]    chr18 71815505-71816528      *
##   [69]    chr18 74060619-74061642      *
##   [70]    chr18 76774213-76777284      *
##   [71]    chr18 76849989-76851012      *
##   [72]    chr18 77377859-77380930      *
##   -------
##   seqinfo: 1 sequence from hg19 genome</code></pre>
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">tamoxifen.greylist</span><span class="op">$</span><span class="va">controls</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "BT474c" "MCF7c"  "T47Dc"  "TAMRc"  "ZR75c"</code></pre>
<p>Now we can apply it:</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.peaks</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.blacklist.html">dba.blacklist</a></span><span class="op">(</span><span class="va">tam.peaks</span>, blacklist<span class="op">=</span><span class="va">DBA_BLACKLIST_HG19</span>,
                           greylist<span class="op">=</span><span class="va">tamoxifen.greylist</span><span class="op">)</span></code></pre></div>
<pre><code>## Genome detected: Hsapiens.UCSC.hg19</code></pre>
<pre><code>## Applying blacklist...</code></pre>
<pre><code>## Removed: 3 of 14102 intervals.</code></pre>
<pre><code>## Master greylist: 72 ranges, 255487 bases</code></pre>
<pre><code>## Removed: 420 of 14099 intervals.</code></pre>
<pre><code>## Removed: 52 merged (of 3795) and 50 (of 2845) consensus.</code></pre>
<p>The greylist results in 52 merged peaks being filtered out (50 in the at-least-two-sample consensus), representing some 420 of the originally supplied peaks.</p>
</div>
</div>
<div id="consensus-peaks-sets-and-counting-reads" class="section level2">
<h2 class="hasAnchor">
<a href="#consensus-peaks-sets-and-counting-reads" class="anchor"></a>Consensus peaks sets and counting reads</h2>
<p>The central vehicle for conducting a quantitative analysis is a <em>binding matrix</em>, with rows representing genomic intervals, columns representing samples, and values representing overlapping read counts (similar to an expression matrix in RNA-seq). To compute this, we need to define the rows in the form of a <em>consensus peak set</em>.</p>
<div id="consensus-peak-set" class="section level3">
<h3 class="hasAnchor">
<a href="#consensus-peak-set" class="anchor"></a>Consensus peak set</h3>
<p>One straightforward way to determine the consensus peaks is to consider genomic intervals that are identified as peaks in one or more of the samples. It can be helpful to make a plot of how many peaks overlap in how many samples:</p>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">olap.rate</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.overlap.html">dba.overlap</a></span><span class="op">(</span><span class="va">tam.peaks</span>, mode<span class="op">=</span><span class="va">DBA_OLAP_RATE</span><span class="op">)</span>
<span class="va">olap.rate</span></code></pre></div>
<pre><code>##  [1] 3743 2795 1731 1350 1037  782  621  455  362  186  119</code></pre>
<div class="sourceCode" id="cb69"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">olap.rate</span>, xlab<span class="op">=</span><span class="st">"Overlapping samples"</span>, ylab<span class="op">=</span><span class="st">"Overlapping peaks"</span>, type<span class="op">=</span><span class="st">"b"</span><span class="op">)</span></code></pre></div>
<p><img src="Quantitative-ChIPseq-Workshop_files/figure-html/rateplot-1.png" width="100%"></p>
<p>This shows that there are 3743 total merged peaks, representing the union of all intervals. At the other extreme, there are 119 peaks that overlap in all 11 samples, representing the intersection of all the samples.</p>
<p>Which should we chose? Given the rigor of the underlying statistical analysis, we can choose a more inclusive consensus set. The default is to make the consensus peak set using peaks identified in at least two samples (2795).</p>
<p>More complex schemes, such as forming a consensus peak set separately from the replicates for each condition and then taking the union of these, are also possible.</p>
<p>The default consensus peak set can be retrieved:</p>
<div class="sourceCode" id="cb70"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">consensus.peaks</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.peakset.html">dba.peakset</a></span><span class="op">(</span><span class="va">tam.peaks</span>, bRetrieve<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span>
<span class="va">consensus.peaks</span><span class="op">[</span>,<span class="fl">0</span><span class="op">]</span></code></pre></div>
<pre><code>## GRanges object with 2795 ranges and 0 metadata columns:
##        seqnames            ranges strand
##           &lt;Rle&gt;         &lt;IRanges&gt;  &lt;Rle&gt;
##      1    chr18       90637-91191      *
##      2    chr18     150145-150725      *
##      3    chr18     150764-151269      *
##      4    chr18     188982-189652      *
##      5    chr18     199684-200400      *
##    ...      ...               ...    ...
##   2791    chr18 77782496-77783186      *
##   2792    chr18 77902962-77903771      *
##   2793    chr18 77955224-77955928      *
##   2794    chr18 77968033-77968822      *
##   2795    chr18 77987044-77988289      *
##   -------
##   seqinfo: 1 sequence from an unspecified genome; no seqlengths</code></pre>
</div>
<div id="counting-overlapping-reads" class="section level3">
<h3 class="hasAnchor">
<a href="#counting-overlapping-reads" class="anchor"></a>Counting overlapping reads</h3>
<p>The next step is to form the binding matrix using the consensus peak and computing overlapping read counts for each peak in each sample, <em>whether or not it was called as a peak in that sample.</em></p>
<p>The function used to accomplish this is <code><a href="https://rdrr.io/pkg/DiffBind/man/dba.count.html">dba.count()</a></code>:</p>
<div class="sourceCode" id="cb72"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.counts</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.count.html">dba.count</a></span><span class="op">(</span><span class="va">tam.peaks</span><span class="op">)</span></code></pre></div>
<p>NB: this call may take some time. You can, alternatively, obtain the results as follows:</p>
<div class="sourceCode" id="cb73"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">tamoxifen_counts</span><span class="op">)</span>
<span class="va">tam.counts</span> <span class="op">&lt;-</span> <span class="va">tamoxifen</span></code></pre></div>
<p><code><a href="https://rdrr.io/pkg/DiffBind/man/dba.count.html">dba.count()</a></code> takes a number of parameter to control it’s default behavior. Here is a list of some important ones:</p>
<ul>
<li>
<strong>peaks</strong> accepts a consensus peak set. We could have used the peak set retrieved above by specifying <code>peaks=consensus.peaks</code>.</li>
<li>
<strong>summits</strong> activates a two-stage counting process. In the first stage, a “summit” is computed for each peak based on the read pileups at each base for each sample the peak was called in. The peak intervals are then re-specified to be a constant interval upstream and downstream of this summit. The default of <code>summits=200</code>, intended for ChIP-seq, results in 401bp peaks (The summit point plus 200bp in each direction). In the second phase reads are re-counted overlapping these intervals.</li>
<li>
<strong>filter</strong> will eliminate consensus peaks with lower than a set threshold of counts. The default <code>filter=1</code> will filter consensus peaks where there is not at least one sample whose RPKM (reads per kilobase per million reads) is greater than 1.</li>
<li>
<strong>bRemoveDuplicates</strong> controls how duplicate alignments (multiple reads mapping to the exact same genomic position) are handled. The default <code>bRemoveDuplicates=FALSE</code> will keep and count duplicates, as DNA enrichment assays often include biologically meaningful duplicate reads (especially when using short read or single-end sequencing).</li>
<li>
<strong>mapQCth</strong> sets a threshold for ignoring low-quality alignment. The default value of <code>mapQCth=15</code> results in all multi-mapped reads (reads that can map to multiple locations in the genome) being ignored.</li>
</ul>
<p>After counting the reads, the DBA object reflects the consensus peak set rather than the original peak data:</p>
<div class="sourceCode" id="cb74"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.counts</span></code></pre></div>
<pre><code>## 11 Samples, 2845 sites in matrix:
##        ID Tissue Factor  Condition  Treatment Replicate   Reads FRiP
## 1  BT4741  BT474     ER  Resistant Full-Media         1  652697 0.16
## 2  BT4742  BT474     ER  Resistant Full-Media         2  663370 0.15
## 3   MCF71   MCF7     ER Responsive Full-Media         1  346429 0.31
## 4   MCF72   MCF7     ER Responsive Full-Media         2  368052 0.19
## 5   MCF73   MCF7     ER Responsive Full-Media         3  466273 0.25
## 6   T47D1   T47D     ER Responsive Full-Media         1  399879 0.11
## 7   T47D2   T47D     ER Responsive Full-Media         2 1475415 0.06
## 8  MCF7r1   MCF7     ER  Resistant Full-Media         1  616630 0.22
## 9  MCF7r2   MCF7     ER  Resistant Full-Media         2  593224 0.14
## 10  ZR751   ZR75     ER Responsive Full-Media         1  706836 0.33
## 11  ZR752   ZR75     ER Responsive Full-Media         2 2575408 0.22</code></pre>
<p>Now all eleven samples have counts for all 2,845 consensus sites. Two columns have been added to the display, showing the total number of aligned <code>Reads</code> in each <code>.bam</code>file, and the Fraction of Reads in Peaks (<code>FRiP</code>) representing the proportion of reads that were counted as overlapping a consensus site.</p>
</div>
</div>
<div id="examining-and-normalizing-the-binding-matrix" class="section level2">
<h2 class="hasAnchor">
<a href="#examining-and-normalizing-the-binding-matrix" class="anchor"></a>Examining and normalizing the binding matrix</h2>
<p>At this stage it is worth looking more closely at certain aspects of the binding matrix in preparation for normalization and modeling.</p>
<div id="plots-to-look-for-a-batch-effect" class="section level3">
<h3 class="hasAnchor">
<a href="#plots-to-look-for-a-batch-effect" class="anchor"></a>Plots to look for a batch effect</h3>
<p>Of particular interest is the presence of technical effects in the experiment, such as batch effects.</p>
<p>We can look at how the samples cluster using heatmaps and PCA plots. A correlation heatmap (in which correlations values between each pair of columns in the binding matrix is calculated) can be shown using <code><a href="https://rdrr.io/pkg/DiffBind/man/dba.plotHeatmap.html">dba.plotHeatmap()</a></code>, which is also the default plot:</p>
<div class="sourceCode" id="cb76"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">tam.counts</span><span class="op">)</span></code></pre></div>
<p><img src="Quantitative-ChIPseq-Workshop_files/figure-html/counthm-1.png" width="100%"></p>
<p>This shows a very high correlation between the replicate for each sample type, which indicates that there is not a large batch effect. The main clustering divides the samples into those derived from the MCF7 cell line, which are all highly correlated, with the other cell lines clustering together. At this point, we do not see a natural clustering into tamoxifen <code>Responsive</code> and <code>Resistant</code> clusters.</p>
<p>We can verify that there is no obvious batch effect with a PCA plot:</p>
<div class="sourceCode" id="cb77"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.plotPCA.html">dba.plotPCA</a></span><span class="op">(</span><span class="va">tam.counts</span>,<span class="va">DBA_REPLICATE</span>, label<span class="op">=</span><span class="va">DBA_TISSUE</span><span class="op">)</span></code></pre></div>
<p><img src="Quantitative-ChIPseq-Workshop_files/figure-html/countPCA-1.png" width="100%"></p>
</div>
<div id="normalization-deault" class="section level3">
<h3 class="hasAnchor">
<a href="#normalization-deault" class="anchor"></a>Normalization (deault)</h3>
<p>The next step is to normalize the data. Normalization of ChIP and ATAC sequencing data is not always straightforward, especially compared to normalization of RNA-seq data. We will look more closely at these issues in a subsequent section. For now we will use the default normalization in <code>DiffBind</code>, which makes minimal assumptions about the data and seeks to “do no harm”.</p>
<p>First let’s make an MA plot of the date before normalization. An MA plot shows how the fold changes between conditions are distributed as the mean concdntration of reads counts increases. For this plot, we’ll compare use the sample sin the <code>Responsive</code>condition as the baseline, and see how the samples in the <code>Resistant</code>condition compare.</p>
<div class="sourceCode" id="cb78"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.plotMA.html">dba.plotMA</a></span><span class="op">(</span><span class="va">tam.counts</span>, bNormalized<span class="op">=</span><span class="cn">FALSE</span>, sub<span class="op">=</span><span class="st">"Non-Normalized"</span>,
           contrast<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>Resistant<span class="op">=</span><span class="va">tam.counts</span><span class="op">$</span><span class="va">masks</span><span class="op">$</span><span class="va">Resistant</span>,
                         Responsive<span class="op">=</span><span class="va">tam.counts</span><span class="op">$</span><span class="va">masks</span><span class="op">$</span><span class="va">Responsive</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="Quantitative-ChIPseq-Workshop_files/figure-html/maraw-1.png" width="100%"> In this plot, each of the consensus site is a point (smoothed), while the the X-axis orders them according to the mean number of<br>
overlapping read counts for the consensus site, and the Y-axis shows the log2 fold change. Points above the 0-fold line (blue) demonstrate greater enrichment of reads in the <code>Resistant</code>condition, while point below the 0-fold line are more enriched int he <code>Responsive</code> condition. The red curve is a loess fit showing the overall trend in the data.</p>
<p>This plots shows that in the raw data, the <code>Responsive</code> condition samples have overall higher concentration of overlapping reads in consensus peaks. This could either be a technical bias, or an indication that there is a loss of ER binding in the tamoxifen resistant condition.</p>
<p>By default, <code>DiffBind</code> normalizes only using the full library sizes of the samples (total aligned reads in the <code>.bam</code>). Perform a default normalization and see how the plot changes:</p>
<div class="sourceCode" id="cb79"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.counts</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.normalize.html">dba.normalize</a></span><span class="op">(</span><span class="va">tam.counts</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.plotMA.html">dba.plotMA</a></span><span class="op">(</span><span class="va">tam.counts</span>, sub<span class="op">=</span><span class="st">"Normalized (Default)"</span>,
           contrast<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>Resistant<span class="op">=</span><span class="va">tam.counts</span><span class="op">$</span><span class="va">masks</span><span class="op">$</span><span class="va">Resistant</span>,
                         Responsive<span class="op">=</span><span class="va">tam.counts</span><span class="op">$</span><span class="va">masks</span><span class="op">$</span><span class="va">Responsive</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="Quantitative-ChIPseq-Workshop_files/figure-html/normdef-1.png" width="100%"></p>
<p>Compared to the non-normalized data, the fold changes are somewhat mnore balanced and moved closer to the central 0-fold line, although the loess fit shows there is still a bias towards greater enrichment in the <code>Responsive</code> condition.</p>
<p>We will consider normalization in more depth after modeling the data, as it is useful to consider the impact of normalization on the modeling results.</p>
</div>
</div>
<div id="modeling-and-testing" class="section level2">
<h2 class="hasAnchor">
<a href="#modeling-and-testing" class="anchor"></a>Modeling and testing</h2>
<p>The core differential analysis in <code>DiffBind</code>is performed by one or more underlying read count modeling Bioconductor packges. The default package is <code>DESeq2</code> <span class="citation">(Love, Huber, and Anders 2014)</span>; the <code>edgeR</code> package <span class="citation">(Robinson, McCarthy, and Smyth 2010)</span> may be also used either as an alternative or in parallel. These packages, developed for modeling RNA-seq read counts, enable GLMs to be fit.</p>
<div id="default-model" class="section level3">
<h3 class="hasAnchor">
<a href="#default-model" class="anchor"></a>Default model</h3>
<p>The <code>DiffBind</code> function <code><a href="https://rdrr.io/pkg/DiffBind/man/dba.contrast.html">dba.contrast()</a></code> is used to specify the model and establish contrasts to be tested against the model. A default model and contrasts(s) can easily be established:</p>
<div class="sourceCode" id="cb80"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.contrast.html">dba.contrast</a></span><span class="op">(</span><span class="va">tam.counts</span><span class="op">)</span></code></pre></div>
<pre><code>## Computing results names...</code></pre>
<div class="sourceCode" id="cb82"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.model</span></code></pre></div>
<pre><code>## 11 Samples, 2845 sites in matrix:
##        ID Tissue Factor  Condition  Treatment Replicate   Reads FRiP
## 1  BT4741  BT474     ER  Resistant Full-Media         1  652697 0.16
## 2  BT4742  BT474     ER  Resistant Full-Media         2  663370 0.15
## 3   MCF71   MCF7     ER Responsive Full-Media         1  346429 0.31
## 4   MCF72   MCF7     ER Responsive Full-Media         2  368052 0.19
## 5   MCF73   MCF7     ER Responsive Full-Media         3  466273 0.25
## 6   T47D1   T47D     ER Responsive Full-Media         1  399879 0.11
## 7   T47D2   T47D     ER Responsive Full-Media         2 1475415 0.06
## 8  MCF7r1   MCF7     ER  Resistant Full-Media         1  616630 0.22
## 9  MCF7r2   MCF7     ER  Resistant Full-Media         2  593224 0.14
## 10  ZR751   ZR75     ER Responsive Full-Media         1  706836 0.33
## 11  ZR752   ZR75     ER Responsive Full-Media         2 2575408 0.22
## 
## Design: [~Condition] | 1 Contrast:
##      Factor     Group Samples     Group2 Samples2
## 1 Condition Resistant       4 Responsive        7</code></pre>
<p>The default model is based on observing that there is only one metadata field, <code>Condition</code>, that has a) multiple values and b) at least three samples having each value. A design formula is established using this factor and a contrast comparing <code>Resistant</code> samples against the <code>Responsive</code> samples, with four samples in the <code>Resistant</code> condition and seven samples in the <code>Responsive</code> condition.</p>
</div>
<div id="fitting-and-testing" class="section level3">
<h3 class="hasAnchor">
<a href="#fitting-and-testing" class="anchor"></a>Fitting and testing</h3>
<p>With the design formula in place, and a contrast established, the model can be fit with <code>DESeq2</code> and tests applied for the contrast:</p>
<div class="sourceCode" id="cb84"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.analyze.html">dba.analyze</a></span><span class="op">(</span><span class="va">tam.model</span><span class="op">)</span></code></pre></div>
<pre><code>## Analyzing...</code></pre>
<pre><code>## gene-wise dispersion estimates</code></pre>
<pre><code>## mean-dispersion relationship</code></pre>
<pre><code>## final dispersion estimates</code></pre>
<div class="sourceCode" id="cb89"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.show.html">dba.show</a></span><span class="op">(</span><span class="va">tam.model</span>,bContrasts<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>##      Factor     Group Samples     Group2 Samples2 DB.DESeq2
## 1 Condition Resistant       4 Responsive        7       246</code></pre>
<p>At the default threshold of <code>FDR &lt; 0.05</code>, some 246 sites are identified as being differentially bound.</p>
</div>
</div>
<div id="examining-analysis-results" class="section level2">
<h2 class="hasAnchor">
<a href="#examining-analysis-results" class="anchor"></a>Examining analysis results</h2>
<p>After conducting an analysis, the results can be examined in a number of ways, including obtaining a report with the differential sites, as well as some useful plots.</p>
<div id="reporting-obtaining-differential-sites" class="section level3">
<h3 class="hasAnchor">
<a href="#reporting-obtaining-differential-sites" class="anchor"></a>Reporting: obtaining differential sites</h3>
<p>The differential sites may be retrieved as a <code>GRanges</code> object:</p>
<div class="sourceCode" id="cb91"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.db</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.report.html">dba.report</a></span><span class="op">(</span><span class="va">tam.model</span><span class="op">)</span>
<span class="va">tam.db</span></code></pre></div>
<pre><code>## GRanges object with 246 ranges and 6 metadata columns:
##        seqnames            ranges strand |      Conc Conc_Resistant
##           &lt;Rle&gt;         &lt;IRanges&gt;  &lt;Rle&gt; | &lt;numeric&gt;      &lt;numeric&gt;
##    976    chr18 26861047-26861447      * |      8.37           4.45
##   2470    chr18 65030123-65030523      * |      6.02           2.66
##   1484    chr18 41369550-41369950      * |      8.26           5.12
##   2452    chr18 64490736-64491136      * |      7.43           3.24
##   2338    chr18 60892950-60893350      * |      8.09           3.45
##    ...      ...               ...    ... .       ...            ...
##   2524    chr18 67565747-67566147      * |      3.80           2.44
##   1221    chr18 33021825-33022225      * |      5.04           2.81
##    433    chr18 11320959-11321359      * |      4.29           5.16
##    235    chr18   7757228-7757628      * |      5.05           6.13
##   1405    chr18 38482793-38483193      * |      4.23           2.03
##        Conc_Responsive      Fold   p-value       FDR
##              &lt;numeric&gt; &lt;numeric&gt; &lt;numeric&gt; &lt;numeric&gt;
##    976            8.99     -3.09  1.82e-08  3.36e-05
##   2470            6.63     -2.86  2.84e-08  3.36e-05
##   1484            8.85     -2.75  3.83e-08  3.36e-05
##   2452            8.05     -3.09  4.82e-08  3.36e-05
##   2338            8.72     -3.13  7.73e-08  4.31e-05
##    ...             ...       ...       ...       ...
##   2524            4.24     -1.30   0.00423    0.0486
##   1221            5.58     -1.46   0.00424    0.0486
##    433            3.38      1.31   0.00429    0.0491
##    235            3.57      1.45   0.00436    0.0497
##   1405            4.76     -1.46   0.00441    0.0500
##   -------
##   seqinfo: 1 sequence from an unspecified genome; no seqlengths</code></pre>
<p>For each site, the genomic interval is reported, as well as the key statistics:</p>
<ul>
<li>
<strong>Conc</strong>: Mean concentration of (normalized) reads across all samples, reported as a log2 value.</li>
<li>
<strong>Conc_Resistant</strong>: Mean concentration of (normalized) reads across the <code>Resistant</code> samples, reported as a log2 value.</li>
<li>
<strong>Conc_Responsive</strong>: Mean concentration of (normalized) reads across the <code>Responsive</code> samples, reported as a log2 value.</li>
<li>
<strong>Fold</strong>: Log2 Fold Change, as computed by <code>DESeq2</code>.</li>
<li>
<strong>p-value</strong>: p-value for the comparison, as computed by <code>DESeq2</code>.</li>
<li>
<strong>FDR</strong>: multiple-testing corrected significance value for the comparison, as computed by <code>DESeq2</code>.</li>
</ul>
<p>We can look at the balance between Gain and Loss sites:</p>
<div class="sourceCode" id="cb93"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">tam.db</span><span class="op">$</span><span class="va">Fold</span><span class="op">&gt;</span><span class="fl">0</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 64</code></pre>
<div class="sourceCode" id="cb95"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">tam.db</span><span class="op">$</span><span class="va">Fold</span><span class="op">&lt;</span><span class="fl">0</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 182</code></pre>
<p>The report object can now be used for downstream analysis, such as motif analysis, annotation to genomic features, etc.</p>
</div>
<div id="plotting-ma-plot" class="section level3">
<h3 class="hasAnchor">
<a href="#plotting-ma-plot" class="anchor"></a>Plotting: MA plot</h3>
<p>After an analysis, it is useful to generate an MA plot with the differential sites superimposed:</p>
<div class="sourceCode" id="cb97"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.plotMA.html">dba.plotMA</a></span><span class="op">(</span><span class="va">tam.model</span><span class="op">)</span></code></pre></div>
<p><img src="Quantitative-ChIPseq-Workshop_files/figure-html/macontrast-1.png" width="100%"></p>
</div>
<div id="plotting-volcano-plot" class="section level3">
<h3 class="hasAnchor">
<a href="#plotting-volcano-plot" class="anchor"></a>Plotting: Volcano plot</h3>
<p>Similar to an MA plot, a volcano plot shows the log fold change (on the X-axis instead fo the Y-axis), compared to the inverse of the FDR on the Y-axis, to show how FDR and LFC are related:</p>
<div class="sourceCode" id="cb98"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.plotVolcano.html">dba.plotVolcano</a></span><span class="op">(</span><span class="va">tam.model</span><span class="op">)</span></code></pre></div>
<p><img src="Quantitative-ChIPseq-Workshop_files/figure-html/volcano-1.png" width="100%"></p>
</div>
<div id="plotting-clustering-correlation-heatmap" class="section level3">
<h3 class="hasAnchor">
<a href="#plotting-clustering-correlation-heatmap" class="anchor"></a>Plotting: Clustering correlation heatmap</h3>
<p>We can also re-visit the clustering plots we originally did on the full binding matrix, except this time only taking differential sites intro consideration:</p>
<div class="sourceCode" id="cb99"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">tam.model</span>, contrast<span class="op">=</span><span class="fl">1</span><span class="op">)</span></code></pre></div>
<p><img src="Quantitative-ChIPseq-Workshop_files/figure-html/corhmcontrast-1.png" width="100%"></p>
<p>As we would hope, the differential sites separate the samples into two clusters, one <code>Resistant</code> and one <code>Responsive</code>.</p>
</div>
<div id="plotting-pca-plot" class="section level3">
<h3 class="hasAnchor">
<a href="#plotting-pca-plot" class="anchor"></a>Plotting: PCA plot</h3>
<p>Likewise, a PCA plot based only on the differential sites shows how the samples can be separated by condition:</p>
<div class="sourceCode" id="cb100"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.plotPCA.html">dba.plotPCA</a></span><span class="op">(</span><span class="va">tam.model</span>, contrast<span class="op">=</span><span class="fl">1</span>, label<span class="op">=</span><span class="va">DBA_TISSUE</span><span class="op">)</span></code></pre></div>
<p><img src="Quantitative-ChIPseq-Workshop_files/figure-html/pcacontrast-1.png" width="100%"></p>
</div>
<div id="plotting-read-concentration-heatmap" class="section level3">
<h3 class="hasAnchor">
<a href="#plotting-read-concentration-heatmap" class="anchor"></a>Plotting: Read concentration heatmap</h3>
<p>In addition to the correlation heatmap, a plot showing the read concentrations can also be generated. In this case we scale the read concentrations for each site, to emphasize the difference between the lowest and highest values:</p>
<div class="sourceCode" id="cb101"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">hmap</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/grDevices/colorRamp.html">colorRampPalette</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"red"</span>, <span class="st">"black"</span>, <span class="st">"green"</span><span class="op">)</span><span class="op">)</span><span class="op">(</span>n <span class="op">=</span> <span class="fl">13</span><span class="op">)</span>
<span class="va">readscores</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.plotHeatmap.html">dba.plotHeatmap</a></span><span class="op">(</span><span class="va">tam.model</span>, contrast<span class="op">=</span><span class="fl">1</span>, correlations<span class="op">=</span><span class="cn">FALSE</span>,
                              scale<span class="op">=</span><span class="st">"row"</span>, colScheme <span class="op">=</span> <span class="va">hmap</span><span class="op">)</span></code></pre></div>
<p><img src="Quantitative-ChIPseq-Workshop_files/figure-html/hmcontrast-1.png" width="100%"></p>
</div>
</div>
<div id="multi-factor-design" class="section level2">
<h2 class="hasAnchor">
<a href="#multi-factor-design" class="anchor"></a>Multi-factor design</h2>
<p>The default design and contrasts may not be the correct ones, as they may not be focused on the factors of interest. In the current case, it turns out that it is important to use a multi-factor design in order to model the use of different cell lines with each condition, and most importantly the fact that a single cell origin (MCF7) is used across conditions.</p>
<p>In the current case, we will change the model to the “correct” multi-factor design before proceeding:</p>
<div class="sourceCode" id="cb102"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.contrast.html">dba.contrast</a></span><span class="op">(</span><span class="va">tam.model</span>, design<span class="op">=</span><span class="st">"~Tissue + Condition"</span><span class="op">)</span></code></pre></div>
<pre><code>## Replacing design and removing analysis.</code></pre>
<pre><code>## Computing results names...</code></pre>
<div class="sourceCode" id="cb105"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.show.html">dba.show</a></span><span class="op">(</span><span class="va">tam.model</span>,bDesign<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "~Tissue + Condition"</code></pre>
<div class="sourceCode" id="cb107"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.analyze.html">dba.analyze</a></span><span class="op">(</span><span class="va">tam.model</span><span class="op">)</span></code></pre></div>
<pre><code>## Analyzing...</code></pre>
<pre><code>## gene-wise dispersion estimates</code></pre>
<pre><code>## mean-dispersion relationship</code></pre>
<pre><code>## final dispersion estimates</code></pre>
<div class="sourceCode" id="cb112"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tam.model</span></code></pre></div>
<pre><code>## 11 Samples, 2845 sites in matrix:
##        ID Tissue Factor  Condition  Treatment Replicate   Reads FRiP
## 1  BT4741  BT474     ER  Resistant Full-Media         1  652697 0.16
## 2  BT4742  BT474     ER  Resistant Full-Media         2  663370 0.15
## 3   MCF71   MCF7     ER Responsive Full-Media         1  346429 0.31
## 4   MCF72   MCF7     ER Responsive Full-Media         2  368052 0.19
## 5   MCF73   MCF7     ER Responsive Full-Media         3  466273 0.25
## 6   T47D1   T47D     ER Responsive Full-Media         1  399879 0.11
## 7   T47D2   T47D     ER Responsive Full-Media         2 1475415 0.06
## 8  MCF7r1   MCF7     ER  Resistant Full-Media         1  616630 0.22
## 9  MCF7r2   MCF7     ER  Resistant Full-Media         2  593224 0.14
## 10  ZR751   ZR75     ER Responsive Full-Media         1  706836 0.33
## 11  ZR752   ZR75     ER Responsive Full-Media         2 2575408 0.22
## 
## Design: [~Tissue + Condition] | 1 Contrast:
##      Factor     Group Samples     Group2 Samples2 DB.DESeq2
## 1 Condition Resistant       4 Responsive        7       783</code></pre>
<p>With the multi-factor model taking into account the underlying tissue types, we now identify 783 differential sites at the default threshold of <code>FDR &lt; 0.05</code>. The resulting MA plot shows these are biased towards loss of binding the in <code>Resistant</code> condition:</p>
<div class="sourceCode" id="cb114"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/DiffBind/man/dba.plotMA.html">dba.plotMA</a></span><span class="op">(</span><span class="va">tam.model</span>, contrast<span class="op">=</span><span class="fl">1</span><span class="op">)</span></code></pre></div>
<p><img src="Quantitative-ChIPseq-Workshop_files/figure-html/mamulti-1.png" width="100%"></p>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references">
<div id="ref-amemiya2019blacklist">
<p>Amemiya, Haley M., Anshul Kundaje, and Alan P. Boyle. 2019. “The ENCODE Blacklist: Identification of Problematic Regions of the Genome.” <em>Scientific Reports</em> 9 (1): 9354.</p>
</div>
<div id="ref-brown2015greylistchip">
<p>Brown, Gord. 2015. “GreyListChIP: Grey Lists–Mask Artefact Regions Based on ChIP Inputs.” <a href="https://doi.org/10.18129/B9.bioc.GreyListChIP">https://doi.org/10.18129/B9.bioc.GreyListChIP</a>.</p>
</div>
<div id="ref-Love2014">
<p>Love, Michael I., Wolfgang Huber, and Simon Anders. 2014. “Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2.” <em>Genome Biology</em> 15 (12): 550. <a href="http://dx.doi.org/10.1186/s13059-014-0550-8">http://dx.doi.org/10.1186/s13059-014-0550-8</a>.</p>
</div>
<div id="ref-lun2016csaw">
<p>Lun, Aaron TL, and Gordon K Smyth. 2016. “Csaw: A Bioconductor Package for Differential Binding Analysis of ChIP-Seq Data Using Sliding Windows.” <em>Nucleic Acids Research</em> 44 (5): e45–e45.</p>
</div>
<div id="ref-Robinson:2010p249">
<p>Robinson, Mark D, Davis J McCarthy, and Gordon K Smyth. 2010. “EdgeR: A Bioconductor Package for Differential Expression Analysis of Digital Gene Expression Data.” <em>Bioinformatics</em> 26 (1): 139–40. <a href="https://doi.org/10.1093/bioinformatics/btp616">https://doi.org/10.1093/bioinformatics/btp616</a>.</p>
</div>
<div id="ref-zhang2008model">
<p>Zhang, Y., T. Liu, C. A. Meyer, J. Eeckhoute, D. S. Johnson, B. E. Bernstein, C. Nussbaum, et al. 2008. “Model-Based Analysis of ChIP-Seq (MACS).” <em>Genome Biol</em> 9 (9): R137.</p>
</div>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Rory Stark.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
